/*
  SDLop -- a lean reimplementation of the SDL3 API: windowing, input, timing.

  GENERATED FILE -- do not edit.  Produced by tools/sdlop.py from the upstream SDL3
  header SDL_pixels.h (3.2.10), which is zlib licensed, Copyright (C) 1997-2025 Sam Lantinga
  and SDL contributors.  Declarations are copied verbatim so that source and binary
  compatibility with SDL3 are exact; the items SDLop does not implement were
  removed (the full list is in tools/dropped.txt).

  In this header: Pixel formats. Everything is a compile-time constant, but only the formats the
 * window-surface path can read/write are actually implemented (see docs/SURFACE.md).
*/

#ifndef SDL_pixels_h_
#define SDL_pixels_h_

#include <SDL3/SDL_begin_code.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SDL_ALPHA_OPAQUE 255

#define SDL_ALPHA_OPAQUE_FLOAT 1.0f

#define SDL_ALPHA_TRANSPARENT 0

#define SDL_ALPHA_TRANSPARENT_FLOAT 0.0f

typedef enum SDL_BitmapOrder
{
 SDL_BITMAPORDER_NONE,
 SDL_BITMAPORDER_4321,
 SDL_BITMAPORDER_1234
} SDL_BitmapOrder;

typedef enum SDL_PackedOrder
{
 SDL_PACKEDORDER_NONE,
 SDL_PACKEDORDER_XRGB,
 SDL_PACKEDORDER_RGBX,
 SDL_PACKEDORDER_ARGB,
 SDL_PACKEDORDER_RGBA,
 SDL_PACKEDORDER_XBGR,
 SDL_PACKEDORDER_BGRX,
 SDL_PACKEDORDER_ABGR,
 SDL_PACKEDORDER_BGRA
} SDL_PackedOrder;

typedef enum SDL_ArrayOrder
{
 SDL_ARRAYORDER_NONE,
 SDL_ARRAYORDER_RGB,
 SDL_ARRAYORDER_RGBA,
 SDL_ARRAYORDER_ARGB,
 SDL_ARRAYORDER_BGR,
 SDL_ARRAYORDER_BGRA,
 SDL_ARRAYORDER_ABGR
} SDL_ArrayOrder;

typedef enum SDL_PackedLayout
{
 SDL_PACKEDLAYOUT_NONE,
 SDL_PACKEDLAYOUT_332,
 SDL_PACKEDLAYOUT_4444,
 SDL_PACKEDLAYOUT_1555,
 SDL_PACKEDLAYOUT_5551,
 SDL_PACKEDLAYOUT_565,
 SDL_PACKEDLAYOUT_8888,
 SDL_PACKEDLAYOUT_2101010,
 SDL_PACKEDLAYOUT_1010102
} SDL_PackedLayout;

#define SDL_DEFINE_PIXELFOURCC(A, B, C, D) SDL_FOURCC(A, B, C, D)

#define SDL_DEFINE_PIXELFORMAT(type, order, layout, bits, bytes) \
 ((1 << 28) | ((type) << 24) | ((order) << 20) | ((layout) << 16) | \
 ((bits) << 8) | ((bytes) << 0))

#define SDL_PIXELFLAG(format) (((format) >> 28) & 0x0F)

#define SDL_PIXELTYPE(format) (((format) >> 24) & 0x0F)

#define SDL_PIXELORDER(format) (((format) >> 20) & 0x0F)

#define SDL_PIXELLAYOUT(format) (((format) >> 16) & 0x0F)

#define SDL_BITSPERPIXEL(format) \
 (SDL_ISPIXELFORMAT_FOURCC(format) ? 0 : (((format) >> 8) & 0xFF))

#define SDL_BYTESPERPIXEL(format) \
 (SDL_ISPIXELFORMAT_FOURCC(format) ? \
 ((((format) == SDL_PIXELFORMAT_YUY2) || \
 ((format) == SDL_PIXELFORMAT_UYVY) || \
 ((format) == SDL_PIXELFORMAT_YVYU) || \
 ((format) == SDL_PIXELFORMAT_P010)) ? 2 : 1) : (((format) >> 0) & 0xFF))

#define SDL_ISPIXELFORMAT_INDEXED(format) \
 (!SDL_ISPIXELFORMAT_FOURCC(format) && \
 ((SDL_PIXELTYPE(format) == SDL_PIXELTYPE_INDEX1) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_INDEX2) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_INDEX4) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_INDEX8)))

#define SDL_ISPIXELFORMAT_PACKED(format) \
 (!SDL_ISPIXELFORMAT_FOURCC(format) && \
 ((SDL_PIXELTYPE(format) == SDL_PIXELTYPE_PACKED8) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_PACKED16) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_PACKED32)))

#define SDL_ISPIXELFORMAT_ARRAY(format) \
 (!SDL_ISPIXELFORMAT_FOURCC(format) && \
 ((SDL_PIXELTYPE(format) == SDL_PIXELTYPE_ARRAYU8) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_ARRAYU16) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_ARRAYU32) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_ARRAYF16) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_ARRAYF32)))

#define SDL_ISPIXELFORMAT_10BIT(format) \
 (!SDL_ISPIXELFORMAT_FOURCC(format) && \
 ((SDL_PIXELTYPE(format) == SDL_PIXELTYPE_PACKED32) && \
 (SDL_PIXELLAYOUT(format) == SDL_PACKEDLAYOUT_2101010)))

#define SDL_ISPIXELFORMAT_FLOAT(format) \
 (!SDL_ISPIXELFORMAT_FOURCC(format) && \
 ((SDL_PIXELTYPE(format) == SDL_PIXELTYPE_ARRAYF16) || \
 (SDL_PIXELTYPE(format) == SDL_PIXELTYPE_ARRAYF32)))

#define SDL_ISPIXELFORMAT_ALPHA(format) \
 ((SDL_ISPIXELFORMAT_PACKED(format) && \
 ((SDL_PIXELORDER(format) == SDL_PACKEDORDER_ARGB) || \
 (SDL_PIXELORDER(format) == SDL_PACKEDORDER_RGBA) || \
 (SDL_PIXELORDER(format) == SDL_PACKEDORDER_ABGR) || \
 (SDL_PIXELORDER(format) == SDL_PACKEDORDER_BGRA))) || \
 (SDL_ISPIXELFORMAT_ARRAY(format) && \
 ((SDL_PIXELORDER(format) == SDL_ARRAYORDER_ARGB) || \
 (SDL_PIXELORDER(format) == SDL_ARRAYORDER_RGBA) || \
 (SDL_PIXELORDER(format) == SDL_ARRAYORDER_ABGR) || \
 (SDL_PIXELORDER(format) == SDL_ARRAYORDER_BGRA))))

#define SDL_ISPIXELFORMAT_FOURCC(format) \
 ((format) && (SDL_PIXELFLAG(format) != 1))

typedef enum SDL_PixelFormat
{
 SDL_PIXELFORMAT_UNKNOWN = 0,
 SDL_PIXELFORMAT_INDEX1LSB = 0x11100100u,

 SDL_PIXELFORMAT_INDEX1MSB = 0x11200100u,

 SDL_PIXELFORMAT_INDEX2LSB = 0x1c100200u,

 SDL_PIXELFORMAT_INDEX2MSB = 0x1c200200u,

 SDL_PIXELFORMAT_INDEX4LSB = 0x12100400u,

 SDL_PIXELFORMAT_INDEX4MSB = 0x12200400u,

 SDL_PIXELFORMAT_INDEX8 = 0x13000801u,

 SDL_PIXELFORMAT_RGB332 = 0x14110801u,

 SDL_PIXELFORMAT_XRGB4444 = 0x15120c02u,

 SDL_PIXELFORMAT_XBGR4444 = 0x15520c02u,

 SDL_PIXELFORMAT_XRGB1555 = 0x15130f02u,

 SDL_PIXELFORMAT_XBGR1555 = 0x15530f02u,

 SDL_PIXELFORMAT_ARGB4444 = 0x15321002u,

 SDL_PIXELFORMAT_RGBA4444 = 0x15421002u,

 SDL_PIXELFORMAT_ABGR4444 = 0x15721002u,

 SDL_PIXELFORMAT_BGRA4444 = 0x15821002u,

 SDL_PIXELFORMAT_ARGB1555 = 0x15331002u,

 SDL_PIXELFORMAT_RGBA5551 = 0x15441002u,

 SDL_PIXELFORMAT_ABGR1555 = 0x15731002u,

 SDL_PIXELFORMAT_BGRA5551 = 0x15841002u,

 SDL_PIXELFORMAT_RGB565 = 0x15151002u,

 SDL_PIXELFORMAT_BGR565 = 0x15551002u,

 SDL_PIXELFORMAT_RGB24 = 0x17101803u,

 SDL_PIXELFORMAT_BGR24 = 0x17401803u,

 SDL_PIXELFORMAT_XRGB8888 = 0x16161804u,

 SDL_PIXELFORMAT_RGBX8888 = 0x16261804u,

 SDL_PIXELFORMAT_XBGR8888 = 0x16561804u,

 SDL_PIXELFORMAT_BGRX8888 = 0x16661804u,

 SDL_PIXELFORMAT_ARGB8888 = 0x16362004u,

 SDL_PIXELFORMAT_RGBA8888 = 0x16462004u,

 SDL_PIXELFORMAT_ABGR8888 = 0x16762004u,

 SDL_PIXELFORMAT_BGRA8888 = 0x16862004u,

 SDL_PIXELFORMAT_XRGB2101010 = 0x16172004u,

 SDL_PIXELFORMAT_XBGR2101010 = 0x16572004u,

 SDL_PIXELFORMAT_ARGB2101010 = 0x16372004u,

 SDL_PIXELFORMAT_ABGR2101010 = 0x16772004u,

 SDL_PIXELFORMAT_RGB48 = 0x18103006u,

 SDL_PIXELFORMAT_BGR48 = 0x18403006u,

 SDL_PIXELFORMAT_RGBA64 = 0x18204008u,

 SDL_PIXELFORMAT_ARGB64 = 0x18304008u,

 SDL_PIXELFORMAT_BGRA64 = 0x18504008u,

 SDL_PIXELFORMAT_ABGR64 = 0x18604008u,

 SDL_PIXELFORMAT_RGB48_FLOAT = 0x1a103006u,

 SDL_PIXELFORMAT_BGR48_FLOAT = 0x1a403006u,

 SDL_PIXELFORMAT_RGBA64_FLOAT = 0x1a204008u,

 SDL_PIXELFORMAT_ARGB64_FLOAT = 0x1a304008u,

 SDL_PIXELFORMAT_BGRA64_FLOAT = 0x1a504008u,

 SDL_PIXELFORMAT_ABGR64_FLOAT = 0x1a604008u,

 SDL_PIXELFORMAT_RGB96_FLOAT = 0x1b10600cu,

 SDL_PIXELFORMAT_BGR96_FLOAT = 0x1b40600cu,

 SDL_PIXELFORMAT_RGBA128_FLOAT = 0x1b208010u,

 SDL_PIXELFORMAT_ARGB128_FLOAT = 0x1b308010u,

 SDL_PIXELFORMAT_BGRA128_FLOAT = 0x1b508010u,

 SDL_PIXELFORMAT_ABGR128_FLOAT = 0x1b608010u,

 SDL_PIXELFORMAT_YV12 = 0x32315659u,

 SDL_PIXELFORMAT_IYUV = 0x56555949u,

 SDL_PIXELFORMAT_YUY2 = 0x32595559u,

 SDL_PIXELFORMAT_UYVY = 0x59565955u,

 SDL_PIXELFORMAT_YVYU = 0x55595659u,

 SDL_PIXELFORMAT_NV12 = 0x3231564eu,

 SDL_PIXELFORMAT_NV21 = 0x3132564eu,

 SDL_PIXELFORMAT_P010 = 0x30313050u,

 SDL_PIXELFORMAT_EXTERNAL_OES = 0x2053454fu,

 SDL_PIXELFORMAT_MJPG = 0x47504a4du,

 #if SDL_BYTEORDER == SDL_BIG_ENDIAN
 SDL_PIXELFORMAT_RGBA32 = SDL_PIXELFORMAT_RGBA8888,
 SDL_PIXELFORMAT_ARGB32 = SDL_PIXELFORMAT_ARGB8888,
 SDL_PIXELFORMAT_BGRA32 = SDL_PIXELFORMAT_BGRA8888,
 SDL_PIXELFORMAT_ABGR32 = SDL_PIXELFORMAT_ABGR8888,
 SDL_PIXELFORMAT_RGBX32 = SDL_PIXELFORMAT_RGBX8888,
 SDL_PIXELFORMAT_XRGB32 = SDL_PIXELFORMAT_XRGB8888,
 SDL_PIXELFORMAT_BGRX32 = SDL_PIXELFORMAT_BGRX8888,
 SDL_PIXELFORMAT_XBGR32 = SDL_PIXELFORMAT_XBGR8888
 #else
 SDL_PIXELFORMAT_RGBA32 = SDL_PIXELFORMAT_ABGR8888,
 SDL_PIXELFORMAT_ARGB32 = SDL_PIXELFORMAT_BGRA8888,
 SDL_PIXELFORMAT_BGRA32 = SDL_PIXELFORMAT_ARGB8888,
 SDL_PIXELFORMAT_ABGR32 = SDL_PIXELFORMAT_RGBA8888,
 SDL_PIXELFORMAT_RGBX32 = SDL_PIXELFORMAT_XBGR8888,
 SDL_PIXELFORMAT_XRGB32 = SDL_PIXELFORMAT_BGRX8888,
 SDL_PIXELFORMAT_BGRX32 = SDL_PIXELFORMAT_XRGB8888,
 SDL_PIXELFORMAT_XBGR32 = SDL_PIXELFORMAT_RGBX8888
 #endif
} SDL_PixelFormat;

typedef enum SDL_ColorType
{
 SDL_COLOR_TYPE_UNKNOWN = 0,
 SDL_COLOR_TYPE_RGB = 1,
 SDL_COLOR_TYPE_YCBCR = 2
} SDL_ColorType;

typedef enum SDL_ColorRange
{
 SDL_COLOR_RANGE_UNKNOWN = 0,
 SDL_COLOR_RANGE_LIMITED = 1,
 SDL_COLOR_RANGE_FULL = 2
} SDL_ColorRange;

typedef enum SDL_ColorPrimaries
{
 SDL_COLOR_PRIMARIES_UNKNOWN = 0,
 SDL_COLOR_PRIMARIES_BT709 = 1,
 SDL_COLOR_PRIMARIES_UNSPECIFIED = 2,
 SDL_COLOR_PRIMARIES_BT470M = 4,
 SDL_COLOR_PRIMARIES_BT470BG = 5,
 SDL_COLOR_PRIMARIES_BT601 = 6,
 SDL_COLOR_PRIMARIES_SMPTE240 = 7,
 SDL_COLOR_PRIMARIES_GENERIC_FILM = 8,
 SDL_COLOR_PRIMARIES_BT2020 = 9,
 SDL_COLOR_PRIMARIES_XYZ = 10,
 SDL_COLOR_PRIMARIES_SMPTE431 = 11,
 SDL_COLOR_PRIMARIES_SMPTE432 = 12,
 SDL_COLOR_PRIMARIES_EBU3213 = 22,
 SDL_COLOR_PRIMARIES_CUSTOM = 31
} SDL_ColorPrimaries;

typedef enum SDL_TransferCharacteristics
{
 SDL_TRANSFER_CHARACTERISTICS_UNKNOWN = 0,
 SDL_TRANSFER_CHARACTERISTICS_BT709 = 1,
 SDL_TRANSFER_CHARACTERISTICS_UNSPECIFIED = 2,
 SDL_TRANSFER_CHARACTERISTICS_GAMMA22 = 4,
 SDL_TRANSFER_CHARACTERISTICS_GAMMA28 = 5,
 SDL_TRANSFER_CHARACTERISTICS_BT601 = 6,
 SDL_TRANSFER_CHARACTERISTICS_SMPTE240 = 7,
 SDL_TRANSFER_CHARACTERISTICS_LINEAR = 8,
 SDL_TRANSFER_CHARACTERISTICS_LOG100 = 9,
 SDL_TRANSFER_CHARACTERISTICS_LOG100_SQRT10 = 10,
 SDL_TRANSFER_CHARACTERISTICS_IEC61966 = 11,
 SDL_TRANSFER_CHARACTERISTICS_BT1361 = 12,
 SDL_TRANSFER_CHARACTERISTICS_SRGB = 13,
 SDL_TRANSFER_CHARACTERISTICS_BT2020_10BIT = 14,
 SDL_TRANSFER_CHARACTERISTICS_BT2020_12BIT = 15,
 SDL_TRANSFER_CHARACTERISTICS_PQ = 16,
 SDL_TRANSFER_CHARACTERISTICS_SMPTE428 = 17,
 SDL_TRANSFER_CHARACTERISTICS_HLG = 18,
 SDL_TRANSFER_CHARACTERISTICS_CUSTOM = 31
} SDL_TransferCharacteristics;

typedef enum SDL_MatrixCoefficients
{
 SDL_MATRIX_COEFFICIENTS_IDENTITY = 0,
 SDL_MATRIX_COEFFICIENTS_BT709 = 1,
 SDL_MATRIX_COEFFICIENTS_UNSPECIFIED = 2,
 SDL_MATRIX_COEFFICIENTS_FCC = 4,
 SDL_MATRIX_COEFFICIENTS_BT470BG = 5,
 SDL_MATRIX_COEFFICIENTS_BT601 = 6,
 SDL_MATRIX_COEFFICIENTS_SMPTE240 = 7,
 SDL_MATRIX_COEFFICIENTS_YCGCO = 8,
 SDL_MATRIX_COEFFICIENTS_BT2020_NCL = 9,
 SDL_MATRIX_COEFFICIENTS_BT2020_CL = 10,
 SDL_MATRIX_COEFFICIENTS_SMPTE2085 = 11,
 SDL_MATRIX_COEFFICIENTS_CHROMA_DERIVED_NCL = 12,
 SDL_MATRIX_COEFFICIENTS_CHROMA_DERIVED_CL = 13,
 SDL_MATRIX_COEFFICIENTS_ICTCP = 14,
 SDL_MATRIX_COEFFICIENTS_CUSTOM = 31
} SDL_MatrixCoefficients;

typedef enum SDL_ChromaLocation
{
 SDL_CHROMA_LOCATION_NONE = 0,
 SDL_CHROMA_LOCATION_LEFT = 1,
 SDL_CHROMA_LOCATION_CENTER = 2,
 SDL_CHROMA_LOCATION_TOPLEFT = 3
} SDL_ChromaLocation;

#define SDL_DEFINE_COLORSPACE(type, range, primaries, transfer, matrix, chroma) \
 (((Uint32)(type) << 28) | ((Uint32)(range) << 24) | ((Uint32)(chroma) << 20) | \
 ((Uint32)(primaries) << 10) | ((Uint32)(transfer) << 5) | ((Uint32)(matrix) << 0))

#define SDL_COLORSPACETYPE(cspace) (SDL_ColorType)(((cspace) >> 28) & 0x0F)

#define SDL_COLORSPACERANGE(cspace) (SDL_ColorRange)(((cspace) >> 24) & 0x0F)

#define SDL_COLORSPACECHROMA(cspace) (SDL_ChromaLocation)(((cspace) >> 20) & 0x0F)

#define SDL_COLORSPACEPRIMARIES(cspace) (SDL_ColorPrimaries)(((cspace) >> 10) & 0x1F)

#define SDL_COLORSPACETRANSFER(cspace) (SDL_TransferCharacteristics)(((cspace) >> 5) & 0x1F)

#define SDL_COLORSPACEMATRIX(cspace) (SDL_MatrixCoefficients)((cspace) & 0x1F)

#define SDL_ISCOLORSPACE_MATRIX_BT601(cspace) (SDL_COLORSPACEMATRIX(cspace) == SDL_MATRIX_COEFFICIENTS_BT601 || SDL_COLORSPACEMATRIX(cspace) == SDL_MATRIX_COEFFICIENTS_BT470BG)

#define SDL_ISCOLORSPACE_MATRIX_BT709(cspace) (SDL_COLORSPACEMATRIX(cspace) == SDL_MATRIX_COEFFICIENTS_BT709)

#define SDL_ISCOLORSPACE_MATRIX_BT2020_NCL(cspace) (SDL_COLORSPACEMATRIX(cspace) == SDL_MATRIX_COEFFICIENTS_BT2020_NCL)

#define SDL_ISCOLORSPACE_LIMITED_RANGE(cspace) (SDL_COLORSPACERANGE(cspace) != SDL_COLOR_RANGE_FULL)

#define SDL_ISCOLORSPACE_FULL_RANGE(cspace) (SDL_COLORSPACERANGE(cspace) == SDL_COLOR_RANGE_FULL)

typedef enum SDL_Colorspace
{
 SDL_COLORSPACE_UNKNOWN = 0,

 SDL_COLORSPACE_SRGB = 0x120005a0u,

 SDL_COLORSPACE_SRGB_LINEAR = 0x12000500u,

 SDL_COLORSPACE_HDR10 = 0x12002600u,

 SDL_COLORSPACE_JPEG = 0x220004c6u,

 SDL_COLORSPACE_BT601_LIMITED = 0x211018c6u,

 SDL_COLORSPACE_BT601_FULL = 0x221018c6u,

 SDL_COLORSPACE_BT709_LIMITED = 0x21100421u,

 SDL_COLORSPACE_BT709_FULL = 0x22100421u,

 SDL_COLORSPACE_BT2020_LIMITED = 0x21102609u,

 SDL_COLORSPACE_BT2020_FULL = 0x22102609u,

 SDL_COLORSPACE_RGB_DEFAULT = SDL_COLORSPACE_SRGB,
 SDL_COLORSPACE_YUV_DEFAULT = SDL_COLORSPACE_JPEG
} SDL_Colorspace;

typedef struct SDL_Color
{
 Uint8 r;
 Uint8 g;
 Uint8 b;
 Uint8 a;
} SDL_Color;

typedef struct SDL_FColor
{
 float r;
 float g;
 float b;
 float a;
} SDL_FColor;

typedef struct SDL_Palette
{
 int ncolors;
 SDL_Color *colors;
 Uint32 version;
 int refcount;
} SDL_Palette;

typedef struct SDL_PixelFormatDetails
{
 SDL_PixelFormat format;
 Uint8 bits_per_pixel;
 Uint8 bytes_per_pixel;
 Uint8 padding[2];
 Uint32 Rmask;
 Uint32 Gmask;
 Uint32 Bmask;
 Uint32 Amask;
 Uint8 Rbits;
 Uint8 Gbits;
 Uint8 Bbits;
 Uint8 Abits;
 Uint8 Rshift;
 Uint8 Gshift;
 Uint8 Bshift;
 Uint8 Ashift;
} SDL_PixelFormatDetails;

extern SDL_DECLSPEC const char * SDLCALL SDL_GetPixelFormatName(SDL_PixelFormat format);

extern SDL_DECLSPEC bool SDLCALL SDL_GetMasksForPixelFormat(SDL_PixelFormat format, int *bpp, Uint32 *Rmask, Uint32 *Gmask, Uint32 *Bmask, Uint32 *Amask);

extern SDL_DECLSPEC SDL_PixelFormat SDLCALL SDL_GetPixelFormatForMasks(int bpp, Uint32 Rmask, Uint32 Gmask, Uint32 Bmask, Uint32 Amask);

extern SDL_DECLSPEC const SDL_PixelFormatDetails * SDLCALL SDL_GetPixelFormatDetails(SDL_PixelFormat format);

extern SDL_DECLSPEC Uint32 SDLCALL SDL_MapRGB(const SDL_PixelFormatDetails *format, const SDL_Palette *palette, Uint8 r, Uint8 g, Uint8 b);

extern SDL_DECLSPEC Uint32 SDLCALL SDL_MapRGBA(const SDL_PixelFormatDetails *format, const SDL_Palette *palette, Uint8 r, Uint8 g, Uint8 b, Uint8 a);

extern SDL_DECLSPEC void SDLCALL SDL_GetRGB(Uint32 pixel, const SDL_PixelFormatDetails *format, const SDL_Palette *palette, Uint8 *r, Uint8 *g, Uint8 *b);

extern SDL_DECLSPEC void SDLCALL SDL_GetRGBA(Uint32 pixel, const SDL_PixelFormatDetails *format, const SDL_Palette *palette, Uint8 *r, Uint8 *g, Uint8 *b, Uint8 *a);

#include <SDL3/SDL_close_code.h>

#ifdef __cplusplus
}
#endif

#endif /* SDL_pixels_h_ */
