#!/usr/bin/env python3
"""Generate src/generated/sdlop_evdev.h from SDL3's Linux scancode table.

The mapping from a Linux evdev keycode to an SDL scancode is *data*, not logic:
upstream keeps it in a generated header (src/events/scancodes_linux.h) and so do
we. Using upstream's table verbatim is what makes
SDL_GetScancodeFromKey()/SDL_GetKeyboardState() agree with SDL3 for every key on
the keyboard, including the keypad and the media keys.

Usage:
    python3 tools/gen_evdev.py                # write src/generated/sdlop_evdev.h
    python3 tools/gen_evdev.py --check        # exit 1 if the file is out of date
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, "tools/reference/scancodes_linux.h")
OUT = os.path.join(ROOT, "src/generated/sdlop_evdev.h")


def parse():
    text = open(TABLE).read()
    entries = {}
    for m in re.finditer(r"/\*\s*(\d+),\s*0x[0-9a-f]+\s*\*/\s*(SDL_SCANCODE_[A-Z0-9_]+)\s*,\s*//\s*([A-Z0-9_]+)",
                         text):
        code = int(m.group(1))
        entries[code] = (m.group(2), m.group(3))
    return entries


def emit(entries):
    size = max(entries) + 1
    out = []
    out.append("/*")
    out.append("  SDLop -- Linux evdev keycode -> SDL scancode table.")
    out.append("")
    out.append("  GENERATED by tools/gen_evdev.py from tools/reference/scancodes_linux.h")
    out.append("  (upstream SDL3 release-3.2.10, src/events/scancodes_linux.h, zlib licence).")
    out.append("  Do not edit: re-run the generator instead.")
    out.append("*/")
    out.append("")
    out.append("#ifndef SDLOP_EVDEV_H")
    out.append("#define SDLOP_EVDEV_H")
    out.append("")
    out.append("#include <SDL3/SDL.h>")
    out.append("")
    out.append("#define SDLOP_EVDEV_KEYCODE_COUNT %d" % size)
    out.append("")
    out.append("/* index: Linux keycode from struct input_event.code */")
    out.append("static const SDL_Scancode sdlop_scancode_from_evdev[SDLOP_EVDEV_KEYCODE_COUNT] = {")
    for code in range(size):
        if code in entries:
            name, evname = entries[code]
            out.append("    %s,   /* %s */" % (name, evname))
        else:
            out.append("    SDL_SCANCODE_UNKNOWN,")
    out.append("};")
    out.append("")
    out.append("#endif /* SDLOP_EVDEV_H */")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = ap.parse_args()

    entries = parse()
    if not entries:
        print("error: could not parse %s" % TABLE, file=sys.stderr)
        return 1
    text = emit(entries)
    if args.check:
        current = open(OUT).read() if os.path.exists(OUT) else ""
        if current != text:
            print("%s is out of date" % os.path.relpath(OUT, ROOT), file=sys.stderr)
            return 1
        print("%s is up to date (%d keycodes)" % (os.path.relpath(OUT, ROOT), len(entries)))
        return 0
    open(OUT, "w").write(text)
    print("wrote %s: %d keycodes, array size %d" % (os.path.relpath(OUT, ROOT), len(entries), max(entries) + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
