#!/usr/bin/env python3
"""
gen_pixelformats.py -- generate src/events/sdlop_pixelformats.h.

Every SDL_PixelFormat in SDL3 is a packed integer (see SDL_DEFINE_PIXELFORMAT), so
the bits-per-pixel, bytes-per-pixel and channel masks can be derived
mechanically. Names come straight from the enum, so SDL_GetPixelFormatName()
covers all 100+ formats even though only the ones the SDLop build can actually
convert are implemented.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INC = os.path.join(ROOT, "include", "SDL3")

# style: name -> (rmask, gmask, bmask, amask) for packed layouts
PACKED = {
    "RGB332": (0xE0, 0x1C, 0x03, 0),
    "ARGB4444": (0x0F00, 0x00F0, 0x000F, 0xF000),
    "RGBA4444": (0xF000, 0x0F00, 0x00F0, 0x000F),
    "ABGR4444": (0x000F, 0x00F0, 0x0F00, 0xF000),
    "BGRA4444": (0x00F0, 0x0F00, 0xF000, 0x000F),
    "ARGB1555": (0x7C00, 0x03E0, 0x001F, 0x8000),
    "RGBA5551": (0xF800, 0x07C0, 0x003E, 0x0001),
    "ABGR1555": (0x001F, 0x03E0, 0x7C00, 0x8000),
    "BGRA5551": (0x003E, 0x07C0, 0xF800, 0x0001),
    "RGB565": (0xF800, 0x07E0, 0x001F, 0),
    "BGR565": (0x001F, 0x07E0, 0xF800, 0),
    "RGB24": (0x00FF0000, 0x0000FF00, 0x000000FF, 0),
    "BGR24": (0x000000FF, 0x0000FF00, 0x00FF0000, 0),
    "XRGB8888": (0x00FF0000, 0x0000FF00, 0x000000FF, 0),
    "RGBX8888": (0x00FF0000, 0x0000FF00, 0x000000FF, 0),
    "XBGR8888": (0x000000FF, 0x0000FF00, 0x00FF0000, 0),
    "BGRX8888": (0x000000FF, 0x0000FF00, 0x00FF0000, 0),
    "ARGB8888": (0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000),
    "RGBA8888": (0xFF000000, 0x00FF0000, 0x0000FF00, 0x000000FF),
    "ABGR8888": (0x000000FF, 0x0000FF00, 0x00FF0000, 0xFF000000),
    "BGRA8888": (0x0000FF00, 0x00FF0000, 0xFF000000, 0x000000FF),
    "ARGB2101010": (0x3FF00000, 0x000FFC00, 0x000003FF, 0xC0000000),
    "ABGR2101010": (0x000003FF, 0x000FFC00, 0x3FF00000, 0xC0000000),
    "XRGB2101010": (0x3FF00000, 0x000FFC00, 0x000003FF, 0),
    "XBGR2101010": (0x000003FF, 0x000FFC00, 0x3FF00000, 0),
}


def parse_formats():
    text = open(os.path.join(INC, "SDL_pixels.h")).read()
    body = re.search(r"typedef enum SDL_PixelFormat\s*\{(.*?)\}\s*SDL_PixelFormat;", text, re.S).group(1)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    formats = []
    for m in re.finditer(r"(SDL_PIXELFORMAT_[A-Z0-9_]+)\s*=\s*([^,\n]+)", body):
        name, expr = m.group(1), m.group(2).strip()
        if name in ("SDL_PIXELFORMAT_UNKNOWN",):
            formats.append((name, 0))
            continue
        try:
            value = int(expr.rstrip("uUlL"), 0)
        except ValueError:
            continue
        formats.append((name, value))
    return formats


def main():
    out_path = os.path.join(ROOT, "src/generated/sdlop_pixelformats.h")
    formats = parse_formats()
    lines = []
    lines.append("/*")
    lines.append("  SDLop -- pixel format table (GENERATED by tools/gen_pixelformats.py).")
    lines.append("")
    lines.append("  name           : every SDL3 format, for SDL_GetPixelFormatName()")
    lines.append("  bits/bytes     : derived from the packed SDL_DEFINE_PIXELFORMAT value")
    lines.append("  masks          : the formats the SDLop build can actually convert")
    lines.append("*/")
    lines.append("")
    lines.append("#ifndef SDLOP_PIXELFORMATS_H")
    lines.append("#define SDLOP_PIXELFORMATS_H")
    lines.append("")
    lines.append("#include <SDL3/SDL.h>")
    lines.append("")
    lines.append("typedef struct SDLOP_PixelFormatInfo")
    lines.append("{")
    lines.append("    SDL_PixelFormat format;")
    lines.append("    const char *name;")
    lines.append("    Uint8 bits;")
    lines.append("    Uint8 bytes;")
    lines.append("    Uint8 order;")
    lines.append("    Uint8 layout;")
    lines.append("    Uint32 rmask, gmask, bmask, amask;")
    lines.append("    bool implemented;")
    lines.append("} SDLOP_PixelFormatInfo;")
    lines.append("")
    lines.append("static const SDLOP_PixelFormatInfo sdlop_pixel_formats[] = {")
    for name, value in formats:
        short = name[len("SDL_PIXELFORMAT_"):]
        if value == 0:
            lines.append('    { 0, "UNKNOWN", 0, 0, 0, 0, 0, 0, 0, 0, false },')
            continue
        bits = (value >> 8) & 0xFF
        nbytes = value & 0xFF
        order = (value >> 20) & 0x0F
        layout = (value >> 16) & 0x0F
        masks = PACKED.get(short)
        if masks:
            r, g, b, a = masks
            impl = "true"
        else:
            r = g = b = a = 0
            # 8/16/32-bit arrays and 8-bit palettes are readable; less common
            # packed/planar/YUV layouts are named but not convertible.
            impl = "true" if short in ("INDEX8", "INDEX4", "INDEX1") else "false"
        lines.append('    { %s, "%s", %d, %d, %d, %d, 0x%08X, 0x%08X, 0x%08X, 0x%08X, %s },'
                     % (name, short, bits, nbytes, order, layout, r, g, b, a, impl))
    lines.append("};")
    lines.append("")
    lines.append("#define SDLOP_NUM_PIXEL_FORMATS %d" % len(formats))
    lines.append("")
    lines.append("#endif /* SDLOP_PIXELFORMATS_H */")
    open(out_path, "w").write("\n".join(lines) + "\n")
    print("wrote %s with %d formats" % (out_path, len(formats)))


if __name__ == "__main__":
    sys.exit(main())
