# CMake generated Testfile for 
# Source directory: /home/user/sdlop
# Build directory: /home/user/sdlop/build-san
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_ring "/home/user/sdlop/build-san/test_ring")
set_tests_properties(test_ring PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;290;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_scancode "/home/user/sdlop/build-san/test_scancode")
set_tests_properties(test_scancode PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;290;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_events "/home/user/sdlop/build-san/test_events")
set_tests_properties(test_events PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;290;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_surface "/home/user/sdlop/build-san/test_surface")
set_tests_properties(test_surface PROPERTIES  ENVIRONMENT "ASAN_OPTIONS=allocator_may_return_null=1" _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;290;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_web "/home/user/sdlop/build-san/test_web")
set_tests_properties(test_web PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;290;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_evdev_uinput "/home/user/sdlop/build-san/test_evdev_uinput")
set_tests_properties(test_evdev_uinput PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;298;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_wayland "/home/user/sdlop/build-san/test_wayland")
set_tests_properties(test_wayland PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;304;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_gl "/home/user/sdlop/build-san/test_gl")
set_tests_properties(test_gl PROPERTIES  ENVIRONMENT "ASAN_OPTIONS=detect_leaks=0" _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;310;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_pointer_lock "/home/user/sdlop/build-san/test_pointer_lock" "/home/user/sdlop/build-san/mini_compositor")
set_tests_properties(test_pointer_lock PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;328;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_touch "/home/user/sdlop/build-san/test_touch" "/home/user/sdlop/build-san/mini_compositor")
set_tests_properties(test_touch PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;335;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(smoke_relative_mode "/home/user/sdlop/build-san/smoke_relative_mode")
set_tests_properties(smoke_relative_mode PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;339;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_gl_matrix "/home/user/sdlop/build-san/test_gl_matrix")
set_tests_properties(test_gl_matrix PROPERTIES  ENVIRONMENT "ASAN_OPTIONS=detect_leaks=0" _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;345;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_vulkan "/home/user/sdlop/build-san/test_vulkan")
set_tests_properties(test_vulkan PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;351;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_vulkan_compute "/home/user/sdlop/build-san/test_vulkan_compute")
set_tests_properties(test_vulkan_compute PROPERTIES  ENVIRONMENT "ASAN_OPTIONS=detect_leaks=0" _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;357;add_test;/home/user/sdlop/CMakeLists.txt;0;")
add_test(test_virtual_input "/home/user/sdlop/build-san/test_virtual_input")
set_tests_properties(test_virtual_input PROPERTIES  _BACKTRACE_TRIPLES "/home/user/sdlop/CMakeLists.txt;386;add_test;/home/user/sdlop/CMakeLists.txt;0;")
