/*
  SDLop -- SDL_keyboard.h: keyboard state, key names and text input.

  Sources of key events (all of them end up in SDLOP_SendKeyEvent):
    * the async evdev worker (src/input/SDL_evdev.c) - primary source;
    * the X11 backend when evdev is unavailable (XWayland, sandboxes);
    * SDL_PushEvent() from an application (SDL_EVENT_KEY_DOWN/KEY_UP).

  Key *names* come from tables generated by tools/gen_keynames.py, so
  SDL_GetScancodeFromName("Left Shift") and friends behave exactly like SDL3.
*/

#include "../sdlop_internal.h"
#include "sdlop_keynames.h"

#include <string.h>

static bool sdlop_keystate[SDL_SCANCODE_COUNT];
static SDL_Keymod sdlop_modstate;

/* The platform key layout (the Wayland compositor's keymap), or NULL when the
   built-in tables are all we have. */
static const SDLOP_KeyLayout *sdlop_key_layout;

void SDLOP_SetKeyLayout(const SDLOP_KeyLayout *layout)
{
    sdlop_key_layout = layout;
}

const SDLOP_KeyLayout *SDLOP_GetKeyLayout(void)
{
    return sdlop_key_layout;
}

/* text input state */
static bool sdlop_text_input_enabled;
static SDL_Window *sdlop_text_input_window;
static SDL_PropertiesID sdlop_text_input_props;
static SDL_Rect sdlop_text_input_rect;
static int sdlop_text_input_cursor = -1;

/* ------------------------------------------------------------------------- */
/* Names                                                                     */
/* ------------------------------------------------------------------------- */

static const SDLOP_KeyName *sdlop_find_name(const SDLOP_KeyName *table, int count, const char *name)
{
    int lo = 0, hi = count - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = SDL_strcasecmp(table[mid].name, name);
        if (cmp == 0) {
            return &table[mid];
        }
        if (cmp < 0) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return NULL;
}

const char *SDL_GetScancodeName(SDL_Scancode scancode)
{
    if (scancode < 0 || scancode >= SDLOP_NUM_SCANCODES || !sdlop_scancode_names[scancode]) {
        SDL_InvalidParamError("scancode");
        return NULL;
    }
    return sdlop_scancode_names[scancode];
}

SDL_Scancode SDL_GetScancodeFromName(const char *name)
{
    const SDLOP_KeyName *found;
    int count = (int)(sizeof(sdlop_scancode_names_by_name) / sizeof(sdlop_scancode_names_by_name[0]));

    if (!name || !name[0]) {
        SDL_InvalidParamError("name");
        return SDL_SCANCODE_UNKNOWN;
    }
    found = sdlop_find_name(sdlop_scancode_names_by_name, count, name);
    return found ? (SDL_Scancode)found->code : SDL_SCANCODE_UNKNOWN;
}

const char *SDL_GetKeyName(SDL_Keycode key)
{
    const SDLOP_KeyName *found;
    int count = (int)(sizeof(sdlop_keynames) / sizeof(sdlop_keynames[0]));

    /* printable ASCII is its own name, like SDL3 */
    if (key == SDLK_UNKNOWN) {
        return "Unknown";
    }
    if (key > 0x20 && key < 0x7F) {
        static char sdlop_ascii_name[2];
        sdlop_ascii_name[0] = (char)key;
        sdlop_ascii_name[1] = '\0';
        return sdlop_ascii_name;
    }
    for (int i = 0; i < count; i++) {
        if (sdlop_keynames[i].code == (SDL_Keycode)key) {
            found = &sdlop_keynames[i];
            return found->name;
        }
    }
    return "Unknown";
}

SDL_Keycode SDL_GetKeyFromName(const char *name)
{
    const SDLOP_KeyName *found;
    int count = (int)(sizeof(sdlop_keynames) / sizeof(sdlop_keynames[0]));

    if (!name || !name[0]) {
        SDL_InvalidParamError("name");
        return SDLK_UNKNOWN;
    }
    if (name[1] == '\0' && (unsigned char)name[0] > 0x20 && (unsigned char)name[0] < 0x7F) {
        /* a single printable character is <-> its own keycode, except that
           letters are stored lowercase in SDLK_* */
        char c = name[0];
        if (c >= 'A' && c <= 'Z') {
            return (SDL_Keycode)(c - 'A' + 'a');
        }
        return (SDL_Keycode)(unsigned char)c;
    }
    for (int i = 0; i < count; i++) {
        if (SDL_strcasecmp(sdlop_keynames[i].name, name) == 0) {
            found = &sdlop_keynames[i];
            return found->code;
        }
    }
    return SDLK_UNKNOWN;
}

/* ------------------------------------------------------------------------- */
/* Scancode <-> keycode                                                      */
/* ------------------------------------------------------------------------- */

static Uint32 sdlop_modifier_scancode_to_keycode(SDL_Scancode scancode)
{
    switch (scancode) {
        case SDL_SCANCODE_LCTRL: return SDLK_LCTRL;
        case SDL_SCANCODE_LSHIFT: return SDLK_LSHIFT;
        case SDL_SCANCODE_LALT: return SDLK_LALT;
        case SDL_SCANCODE_LGUI: return SDLK_LGUI;
        case SDL_SCANCODE_RCTRL: return SDLK_RCTRL;
        case SDL_SCANCODE_RSHIFT: return SDLK_RSHIFT;
        case SDL_SCANCODE_RALT: return SDLK_RALT;
        case SDL_SCANCODE_RGUI: return SDLK_RGUI;
        default: break;
    }
    return 0;
}

SDL_Keycode SDL_GetKeyFromScancode(SDL_Scancode scancode, SDL_Keymod modstate, bool key_event)
{
    Uint32 base;

    (void)key_event;
    if (scancode < 0 || scancode >= SDLOP_NUM_SCANCODES) {
        SDL_InvalidParamError("scancode");
        return SDLK_UNKNOWN;
    }
    base = (Uint32)sdlop_modifier_scancode_to_keycode(scancode);
    if (!base) {
        base = (Uint32)sdlop_keycode_for_scancode[scancode];
    }
    if (base == 0) {
        return SDLK_UNKNOWN;
    }

    if (modstate & SDL_KMOD_SHIFT) {
        Uint32 shifted = (Uint32)sdlop_shifted_keycode_for_scancode[scancode];
        if (shifted) {
            return (SDL_Keycode)shifted;
        }
    }
    if (modstate & SDL_KMOD_CAPS) {
        if (base >= 'a' && base <= 'z') {
            return (SDL_Keycode)(base - 'a' + 'A');
        }
    }
    return (SDL_Keycode)base;
}

SDL_Scancode SDL_GetScancodeFromKey(SDL_Keycode key, SDL_Keymod *modstate)
{
    SDL_Scancode scancode = SDL_SCANCODE_UNKNOWN;
    Uint32 search = (Uint32)key;

    if (modstate) {
        *modstate = SDL_KMOD_NONE;
    }

    /* uppercase letters and shifted characters map back to the unshifted key */
    if (search >= 'A' && search <= 'Z') {
        if (modstate) {
            *modstate |= SDL_KMOD_SHIFT;
        }
        search = search - 'A' + 'a';
    } else if (search > 0x20 && search < 0x7F) {
        for (int i = 0; i < SDLOP_NUM_SCANCODES; i++) {
            if ((Uint32)sdlop_shifted_keycode_for_scancode[i] == search) {
                if (modstate) {
                    *modstate |= SDL_KMOD_SHIFT;
                }
                search = (Uint32)sdlop_keycode_for_scancode[i];
                break;
            }
        }
    }

    for (int i = 0; i < SDLOP_NUM_SCANCODES; i++) {
        if ((Uint32)sdlop_keycode_for_scancode[i] == search) {
            scancode = (SDL_Scancode)i;
            break;
        }
    }
    /* keypad keys carry SDL_SCANCODE_MASK, which the table already reflects */
    return scancode;
}

/* ------------------------------------------------------------------------- */
/* State                                                                     */
/* ------------------------------------------------------------------------- */

const bool *SDL_GetKeyboardState(int *numkeys)
{
    if (numkeys) {
        *numkeys = SDL_SCANCODE_COUNT;
    }
    return sdlop_keystate;
}

SDL_Keymod SDL_GetModState(void)
{
    return sdlop_modstate;
}

void SDL_SetModState(SDL_Keymod modstate)
{
    sdlop_modstate = modstate;
}

void SDL_ResetKeyboard(void)
{
    memset(sdlop_keystate, 0, sizeof(sdlop_keystate));
}

void SDLOP_ResetKeyboardState(void)
{
    memset(sdlop_keystate, 0, sizeof(sdlop_keystate));
    sdlop_modstate = SDL_KMOD_NONE;
    /* the compositor/window manager keeps its own idea of the modifier state,
       so clear ours again on the next key event rather than faking releases */
}

bool SDLOP_KeyboardStateGet(SDL_Scancode scancode)
{
    if (scancode < 0 || scancode >= SDL_SCANCODE_COUNT) {
        return false;
    }
    return sdlop_keystate[scancode];
}

void SDLOP_SetKeyboardFocus(SDL_Window *window)
{
    if (sdlop_text_input_window && sdlop_text_input_window != window) {
        /* text input follows the keyboard focus */
        sdlop_text_input_window = window;
    }
}

static SDL_Keymod sdlop_modstate_for_scancode(SDL_Scancode scancode, bool down)
{
    SDL_Keymod bit = SDL_KMOD_NONE;
    switch (scancode) {
        case SDL_SCANCODE_LSHIFT: bit = SDL_KMOD_LSHIFT; break;
        case SDL_SCANCODE_RSHIFT: bit = SDL_KMOD_RSHIFT; break;
        case SDL_SCANCODE_LCTRL: bit = SDL_KMOD_LCTRL; break;
        case SDL_SCANCODE_RCTRL: bit = SDL_KMOD_RCTRL; break;
        case SDL_SCANCODE_LALT: bit = SDL_KMOD_LALT; break;
        case SDL_SCANCODE_RALT: bit = SDL_KMOD_RALT; break;
        case SDL_SCANCODE_LGUI: bit = SDL_KMOD_LGUI; break;
        case SDL_SCANCODE_RGUI: bit = SDL_KMOD_RGUI; break;
        case SDL_SCANCODE_NUMLOCKCLEAR: bit = SDL_KMOD_NUM; break;
        case SDL_SCANCODE_CAPSLOCK: bit = SDL_KMOD_CAPS; break;
        case SDL_SCANCODE_MODE: bit = SDL_KMOD_MODE; break;
        case SDL_SCANCODE_SCROLLLOCK: bit = SDL_KMOD_SCROLL; break;
        default: return SDL_KMOD_NONE;
    }
    if (down) {
        sdlop_modstate |= bit;
    } else {
        /* num/caps/scroll are toggles: the caller decides by passing the state
           it wants, so only clear the plain modifiers here */
        if (bit != SDL_KMOD_CAPS && bit != SDL_KMOD_NUM && bit != SDL_KMOD_SCROLL) {
            sdlop_modstate &= (SDL_Keymod)~bit;
        }
    }
    return bit;
}

void SDLOP_SetModStateBit(SDL_Keymod bit, bool down)
{
    if (down) {
        sdlop_modstate |= bit;
    } else {
        sdlop_modstate &= (SDL_Keymod)~bit;
    }
}

void SDLOP_SendKeyEvent(SDL_Scancode scancode, SDL_Keycode keycode, SDL_Keymod modstate,
                        bool down, bool repeat, Uint64 timestamp, Uint32 evdev_code)
{
    SDL_Event event;
    SDL_Window *focus = SDLOP_GetKeyboardFocusWindow();

    if (scancode < 0 || scancode >= SDL_SCANCODE_COUNT) {
        return;
    }

    /* A layout the platform provided wins over the built-in tables: it is the
       only way to get "q"/"a"/"z" right on a non-US keyboard, and it already
       accounts for the current modifier state. */
    if (keycode == SDLK_UNKNOWN && evdev_code && sdlop_key_layout &&
        sdlop_key_layout->keycode_from_evdev) {
        keycode = sdlop_key_layout->keycode_from_evdev(evdev_code);
    }

    if (down) {
        if (sdlop_keystate[scancode] && !repeat) {
            /* the key was already down and this is not a repeat: the app missed
               the release (focus change); treat it as a fresh press */
            sdlop_keystate[scancode] = false;
        }
        sdlop_keystate[scancode] = true;
    } else {
        if (repeat) {
            return;
        }
        sdlop_keystate[scancode] = false;
    }

    sdlop_modstate_for_scancode(scancode, down);
    if (modstate != SDL_KMOD_NONE && !(scancode == SDL_SCANCODE_CAPSLOCK)) {
        sdlop_modstate = modstate;
    }

    /* SDL3 only reports key repeats for apps that asked for text input */
    if (repeat && !sdlop_text_input_enabled) {
        return;
    }

    memset(&event, 0, sizeof(event));
    event.type = down ? SDL_EVENT_KEY_DOWN : SDL_EVENT_KEY_UP;
    event.key.timestamp = timestamp;
    event.key.windowID = focus ? focus->id : 0;
    event.key.which = 1;
    event.key.scancode = scancode;
    event.key.key = keycode ? keycode : SDL_GetKeyFromScancode(scancode, sdlop_modstate, true);
    event.key.mod = sdlop_modstate;
    event.key.down = down;
    event.key.repeat = repeat;
    SDLOP_PushEvent(&event);

    SDLOP_HandleTextInputForKey(scancode, event.key.key, evdev_code, down, timestamp);
}

void SDLOP_SendKeymapChanged(Uint64 timestamp)
{
    SDL_Event event;
    memset(&event, 0, sizeof(event));
    event.type = SDL_EVENT_KEYMAP_CHANGED;
    event.common.timestamp = timestamp;
    SDLOP_PushEvent(&event);
}

/* ------------------------------------------------------------------------- */
/* Text input                                                                */
/* ------------------------------------------------------------------------- */

bool SDL_StartTextInput(SDL_Window *window)
{
    return SDL_StartTextInputWithProperties(window, 0);
}

bool SDL_StartTextInputWithProperties(SDL_Window *window, SDL_PropertiesID props)
{
    if (window && !SDL_GetWindowFromID(SDL_GetWindowID(window))) {
        return SDL_InvalidParamError("window");
    }
    sdlop_text_input_enabled = true;
    sdlop_text_input_window = window ? window : SDLOP_GetKeyboardFocusWindow();
    sdlop_text_input_props = props;
    sdlop_text_input_rect.x = 0;
    sdlop_text_input_rect.y = 0;
    sdlop_text_input_rect.w = 0;
    sdlop_text_input_rect.h = 0;
    sdlop_text_input_cursor = -1;
    return true;
}

bool SDL_TextInputActive(SDL_Window *window)
{
    if (!sdlop_text_input_enabled) {
        return false;
    }
    if (!window) {
        return true;
    }
    return sdlop_text_input_window == window;
}

bool SDL_StopTextInput(SDL_Window *window)
{
    if (window && sdlop_text_input_window && sdlop_text_input_window != window) {
        return true;                   /* another window owns text input */
    }
    sdlop_text_input_enabled = false;
    sdlop_text_input_window = NULL;
    sdlop_text_input_props = 0;
    return true;
}

bool SDL_ClearComposition(SDL_Window *window)
{
    if (!SDL_TextInputActive(window)) {
        return SDL_SetError("Text input is not active");
    }
    /* the SDLop build has no preedit buffer of its own: the compositor's
       preedit is never forwarded, so there is nothing to clear */
    return true;
}

bool SDL_SetTextInputArea(SDL_Window *window, const SDL_Rect *rect, int cursor)
{
    if (rect) {
        sdlop_text_input_rect = *rect;
    } else {
        sdlop_text_input_rect.x = sdlop_text_input_rect.y = 0;
        sdlop_text_input_rect.w = sdlop_text_input_rect.h = 0;
    }
    sdlop_text_input_cursor = cursor;
    (void)window;
    return true;
}

bool SDL_GetTextInputArea(SDL_Window *window, SDL_Rect *rect, int *cursor)
{
    (void)window;
    if (rect) {
        *rect = sdlop_text_input_rect;
    }
    if (cursor) {
        *cursor = sdlop_text_input_cursor;
    }
    return true;
}

bool SDL_HasScreenKeyboardSupport(void)
{
    /* desktop Linux: the compositor may offer an on-screen keyboard, but nothing
       in the SDLop build can query it; report what SDL3 reports for desktops. */
    return false;
}

bool SDL_ScreenKeyboardShown(SDL_Window *window)
{
    (void)window;
    return false;
}

bool SDLOP_TextInputActiveForWindow(SDL_Window *window)
{
    return SDL_TextInputActive(window);
}
